#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=5

# Run everything from the repo root, wherever the script was invoked from.
REPO_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$REPO_DIR"
ENV_FILE="$REPO_DIR/.deploy.env"

REPO_NAME="wage-beauty-school"

banner "Publish Wage Beauty School to GitHub Pages"

# ── Stage 1 ──────────────────────────────────────────────────────────────
stage "Create a free GitHub account"
say "GitHub will host the site for free. If you already have an account,"
say "just enter your username when asked and skip the sign-up form."
open_url "https://github.com/signup"
step "Enter your email, then a password, then choose a username."
note "The username becomes part of your web address, so pick carefully:"
note "lowercase letters, numbers and hyphens only (e.g. wage-beauty)."
step "Solve the puzzle, then open the verification email and enter the code."
ask GITHUB_USERNAME "Your GitHub username:"
GITHUB_USERNAME="$(printf '%s' "$GITHUB_USERNAME" | tr -d '[:space:]')"
if [[ -z "$GITHUB_USERNAME" ]]; then
  warn "No username entered. Re-run the script when you have one."
  exit 1
fi
write_env GITHUB_USERNAME "$GITHUB_USERNAME"
SITE_URL="https://${GITHUB_USERNAME}.github.io/${REPO_NAME}/"
REMOTE_URL="https://github.com/${GITHUB_USERNAME}/${REPO_NAME}.git"

# ── Stage 2 ──────────────────────────────────────────────────────────────
stage "Create an empty repository"
say "A repository ('repo') is the folder GitHub keeps your site in."
open_url "https://github.com/new"
step "Repository name:  ${BOLD}${REPO_NAME}${RESET}"
step "Set it to ${BOLD}Public${RESET} (GitHub Pages is free only for public repos)."
warn "Leave every checkbox OFF: no README, no .gitignore, no license."
note "The repo must start empty or the upload in the next step will be rejected."
step "Click 'Create repository'."
pause "Done? Press Enter when the empty repo page is open."
write_env GITHUB_REPO "$REPO_NAME"

# ── Stage 3 ──────────────────────────────────────────────────────────────
stage "Upload the site"
say "This connects your local folder to the GitHub repo and uploads it."
warn "The first upload opens a browser window asking you to authorise Git."
say "Sign in there and click 'Authorize' — then come back here."
pause "Press Enter to start the upload."
git branch -M main
if git remote get-url origin >/dev/null 2>&1; then
  git remote set-url origin "$REMOTE_URL"
else
  git remote add origin "$REMOTE_URL"
fi
say ""
if git push -u origin main; then
  say ""
  printf '  %s✓ upload complete%s\n' "$GREEN" "$RESET"
else
  say ""
  warn "The upload did not finish."
  note "Common causes: the repo was created with a README (delete it and"
  note "recreate empty), or the browser authorisation was cancelled."
  note "Fix that, then run this script again — it picks up where it left off."
  exit 1
fi
if ! git ls-remote --heads origin main | grep -q main; then
  warn "Could not confirm the upload on GitHub. Check the repo page, then re-run."
  exit 1
fi

# ── Stage 4 ──────────────────────────────────────────────────────────────
stage "Turn on GitHub Pages"
say "This tells GitHub to serve the uploaded files as a website."
open_url "https://github.com/${GITHUB_USERNAME}/${REPO_NAME}/settings/pages"
step "Under 'Build and deployment', set ${BOLD}Source${RESET} to 'Deploy from a branch'."
step "Set ${BOLD}Branch${RESET} to 'main' and the folder to '/ (root)'."
step "Click ${BOLD}Save${RESET}."
pause "Press Enter once you've clicked Save."

# ── Stage 5 ──────────────────────────────────────────────────────────────
stage "Wait for the site to go live"
say "GitHub is now building the site. This usually takes 1–3 minutes."
say "Checking $SITE_URL"
say ""
LIVE=""
for _ in $(seq 1 24); do
  code="$(curl -s -o /dev/null -w '%{http_code}' "$SITE_URL" || true)"
  if [[ "$code" == "200" ]]; then LIVE="yes"; break; fi
  printf '  %s… not ready yet (got %s), waiting 15s%s\n' "$DIM" "${code:-no response}" "$RESET"
  sleep 15
done
say ""
if [[ -n "$LIVE" ]]; then
  printf '  %s✓ the School is live%s\n' "$GREEN" "$RESET"
  open_url "$SITE_URL"
else
  warn "Not live yet after a few minutes — this is common on the very first build."
  note "Give it up to 10 minutes, then open the address below. If it still 404s,"
  note "check the repo's Settings → Pages for a green 'Your site is live' banner."
fi
say ""
printf '  %s%sShare this address:%s\n' "$BOLD" "$BLUE" "$RESET"
printf '  %s%s%s\n' "$BOLD" "$SITE_URL" "$RESET"

finish
say "From now on, to publish changes you make locally:"
note "  git add -A && git commit -m \"describe the change\" && git push"
